// Catalogue Data
export const mockCatalogues = [
  {
    id: "1",
    factoryName: "Tata Steel Industries",
    catalogueName: "Steel Products Q1 2026",
    uploadDate: "2026-02-15",
    totalProducts: 245,
    status: "Processed",
    factoryLogo: "TS",
    processedProducts: 245,
    accuracy: 97.5,
    processingTime: "3m 24s",
  },
  {
    id: "2",
    factoryName: "Reliance Polymers",
    catalogueName: "Plastic Raw Materials",
    uploadDate: "2026-02-14",
    totalProducts: 189,
    status: "Processed",
    factoryLogo: "RP",
    processedProducts: 189,
    accuracy: 95.2,
    processingTime: "2m 45s",
  },
  {
    id: "3",
    factoryName: "Mahindra Auto Parts",
    catalogueName: "Vehicle Components 2026",
    uploadDate: "2026-02-16",
    totalProducts: 342,
    status: "Pending",
    factoryLogo: "MA",
    processedProducts: 210,
    accuracy: 0,
    processingTime: "-",
  },
  {
    id: "4",
    factoryName: "Asian Paints Ltd",
    catalogueName: "Industrial Paints Catalog",
    uploadDate: "2026-02-13",
    totalProducts: 156,
    status: "Failed",
    factoryLogo: "AP",
    processedProducts: 0,
    accuracy: 0,
    processingTime: "-",
  },
  {
    id: "5",
    factoryName: "Jindal Textiles",
    catalogueName: "Cotton Fabrics Collection",
    uploadDate: "2026-02-12",
    totalProducts: 428,
    status: "Processed",
    factoryLogo: "JT",
    processedProducts: 428,
    accuracy: 98.1,
    processingTime: "5m 12s",
  },
  {
    id: "6",
    factoryName: "Bharti Electronics",
    catalogueName: "Circuit Components",
    uploadDate: "2026-02-11",
    totalProducts: 523,
    status: "Processed",
    factoryLogo: "BE",
    processedProducts: 523,
    accuracy: 96.8,
    processingTime: "6m 8s",
  },
];


// Products Data
export const mockProducts = [
  {
    id: "p1",
    image: "steel beam",
    name: "Heavy Duty Steel I-Beam 200mm",
    category: "Construction Steel",
    mrp: 15000,
    dealerPrice: 12500,
    gst: 18,
    stock: 450,
    description:
      "High-grade structural steel I-beam suitable for industrial construction",
    manufacturer: "Tata Steel Industries",
    hsn: "72163100",
    confidence: 98.5,
    catalogueId: "1",
  },
  {
    id: "p2",
    image: "steel rod",
    name: "TMT Steel Rods 12mm (Fe 500D)",
    category: "Construction Steel",
    mrp: 48000,
    dealerPrice: 45000,
    gst: 18,
    stock: 850,
    description:
      "Thermo-mechanically treated steel bars for reinforced concrete",
    manufacturer: "Tata Steel Industries",
    hsn: "72142000",
    confidence: 97.2,
    catalogueId: "1",
  },
  {
    id: "p3",
    image: "plastic granules",
    name: "HDPE Granules Natural Grade",
    category: "Plastic Raw Materials",
    mrp: 95000,
    dealerPrice: 88000,
    gst: 18,
    stock: 1200,
    description:
      "High-density polyethylene granules for injection molding",
    manufacturer: "Reliance Polymers",
    hsn: "39012000",
    confidence: 96.8,
    catalogueId: "2",
  },
  {
    id: "p4",
    image: "pvc pipes",
    name: "PVC Resin SG-5 Grade",
    category: "Plastic Raw Materials",
    mrp: 72000,
    dealerPrice: 68000,
    gst: 18,
    stock: 680,
    description:
      "Suspension grade PVC resin for pipe manufacturing",
    manufacturer: "Reliance Polymers",
    hsn: "39041000",
    confidence: 94.5,
    catalogueId: "2",
  },
];


// Analytics Data
export const analyticsData = {
  totalCatalogues: 156,
  totalProducts: 24567,
  averageAccuracy: 96.2,
  averageProcessingTime: "4m 32s",
  failedCatalogues: 8,

  monthlyUploads: [
    { month: "Aug", uploads: 18, products: 3240 },
    { month: "Sep", uploads: 22, products: 4125 },
    { month: "Oct", uploads: 28, products: 5340 },
    { month: "Nov", uploads: 25, products: 4680 },
    { month: "Dec", uploads: 31, products: 6120 },
    { month: "Jan", uploads: 26, products: 4890 },
    { month: "Feb", uploads: 6, products: 1172 },
  ],

  accuracyTrend: [
    { month: "Aug", accuracy: 93.5 },
    { month: "Sep", accuracy: 94.2 },
    { month: "Oct", accuracy: 95.1 },
    { month: "Nov", accuracy: 95.8 },
    { month: "Dec", accuracy: 96.3 },
    { month: "Jan", accuracy: 96.5 },
    { month: "Feb", accuracy: 96.2 },
  ],

  categoryBreakdown: [
    { category: "Construction", value: 6234 },
    { category: "Electronics", value: 5123 },
    { category: "Textiles", value: 4567 },
    { category: "Auto Parts", value: 3890 },
    { category: "Chemicals", value: 2456 },
    { category: "Others", value: 2297 },
  ],
};
